// Code generated by mockery v1.0.0. DO NOT EDIT.

package skywallet

import mock "github.com/stretchr/testify/mock"

// MockTransactionSigner is an autogenerated mock type for the TransactionSigner type
type MockTransactionSigner struct {
	mock.Mock
}

// Sign provides a mock function with given fields:
func (_m *MockTransactionSigner) Sign() ([]string, error) {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
